version: "3.7"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    ports:
      -8080:8080
    command: npm start

  caddy:
    image: 
      caddy: "2.5.2"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - 
    depends_on:
      - app

volumes:
  caddy_data:
    external: true
  caddy_config:
